In [96]:
import numpy as np
d = 7
d_k = 10
d_v = 5
word_1 = np.random.normal(0, 1, size=(1, d))
word_2 = np.random.normal(0, 1, size=(1, d))
word_3 = np.random.normal(0, 1, size=(1, d))
word_4 = np.random.normal(0, 1, size=(1, d))

In [97]:
np.random.seed(0)

W_Q = np.random.normal(0, 1, size=(d, d_k))
W_K = np.random.normal(0, 1, size=(d, d_k))
W_V = np.random.normal(0, 1, size=(d, d_v))

In [123]:
q_1 = word_1 @ W_Q
k_1 = word_1 @ W_K
v_1 = word_1 @ W_V

q_2 = word_2 @ W_Q
k_2 = word_2 @ W_K
v_2 = word_2 @ W_V

q_3 = word_3 @ W_Q
k_3 = word_3 @ W_K
v_3 = word_3 @ W_V

q_4 = word_4 @ W_Q
k_4 = word_4 @ W_K
v_4 = word_4 @ W_V

In [124]:
k_1.shape

(1, 10)

In [125]:
attn_scores = np.array([np.dot(q_1, k_1.T), np.dot(q_1, k_2.T), np.dot(q_1, k_3.T), np.dot(q_1, k_4.T)])

In [133]:
from scipy.special import softmax

weights = softmax(attn_scores / k_1.shape[0] ** 0.5) # var(dot(q, k)) = d_k, var(dot(q, k) / sqrt(d_k)) = 1
attention = (weights[0] * v_1) + (weights[1] * v_2) + (weights[2] * v_3) + (weights[3] * v_4)
print(attention)

[[ 0.9769109  -3.23957895  0.11956248  4.06694761  0.59151333]]


In [153]:
X = np.concatenate([word_1, word_2, word_3, word_4])

Q = X @ W_Q
K = X @ W_K
V = X @ W_V

scores = Q @ K.T


'''
[[score1]
[score2]
...
]
'''
weights = softmax(scores / K.shape[1] ** 0.5, axis=1) 

attention = weights @ V

print(attention)

[[ 0.54171139 -2.32534376 -0.53255017  3.50681119  0.4224472 ]
 [ 0.85981335 -2.96807095 -0.03262619  3.89949033  0.54038676]
 [ 2.79540653 -7.49766691 -3.04395933  4.71897613  2.74293518]
 [ 1.58162268 -4.70290806 -1.76520953  4.03062347  1.51134194]]


#### memo on softmax and aggregation functions' axis

In [155]:
np.sum(weights, axis=1, keepdims=True)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [151]:
test = np.array([[1, 2, 3], [4, 5, 6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
np.sum(test, axis=0, keepdims=True) # when aggregating on an axis, the axis size becomes 1 after the operation.

array([[5, 7, 9]])